version: '3'

services:
    node:
        build:
            context: ./Dockerfiles
            dockerfile: ${NODE_DOCKERFILE}
        image: ${NODE_IMAGE}
        container_name: ${NODE_CONTAINER_NAME:-node}
        volumes:
            - ./src:/var/www
        ports:
            - "33000:3000"
        tty: true