FROM node:20.8.0

MAINTAINER zhoukan "xiningbank@gmail.com"

# ENV LANG C.UTF-8
RUN npm install cnpm -g --registry=http://registry.npm.taobao.org
RUN npm install npm@10.2.0 -g
RUN cnpm install webpack -g
RUN cnpm install webpack@5.88.2 --save-dev
RUN cnpm install cache-loader --save-dev
RUN cnpm rebuild node-sass

RUN echo "alias ll='ls -lh --color=auto'" >> ~/.bashrc
